version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      development:
        patterns:
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "@testing-library/*"
      expo:
        patterns:
          - "expo*"
          - "@expo/*"
      react:
        patterns:
          - "react"
          - "react-*"
          - "@react-*"